---
title: "Lab grade analysis"
autor: "Hugo Sparrman"
format: html
editor: visual
echo: false 
---


```{r}
library(here)
here::i_am("r-101-grade-analysis.Rproj")
library(tidyr)
library(dplyr)
library(vroom)
library(ggplot2)
library(stringr)
```

## Question 1

```{r}
grades <- vroom(here("grades.csv"))
```

## Question 2 

```{r, message=FALSE}
summary_grades<-grades|>
  summarise(Mean = mean(Exam, na.rm = T),
            Median = median(Exam, na.rm = T),
            Min = min(Exam, na.rm = T),
            Max = max(Exam, na.rm = T))

knitr::kable(summary_grades, caption = "Summary statistics of the exam grades")
```

## Question 3 

```{r}
skipping_class<-grades|>
  filter(is.na(Exam))|>nrow()
```

`r skipping_class` did not go to the exam.

## Question 4 

```{r}
grades|>
  drop_na(Exam)|>
  ggplot(aes(x = Exam))+
  geom_bar()+
  xlab("Exam Score")+
  ylab("Count")+
  ggtitle("Exam grade distribution")

```
## Question 5

```{r}
n_students <- grades|>
  group_by(Group)|>
  summarise(N = n())
knitr::kable(n_students, caption = "Number of students in each group")
```

## Quetion 6

```{r}
n_students|>
  ggplot(aes(x = Group, y = N))+
  geom_col()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

## Question 7 

```{r}
grades|> drop_na(Exam)|>
  ggplot(aes(x = Group, y = Exam))+
  geom_boxplot()+
  ggtitle("Conditional grade distribution")+
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        plot.title = element_text(hjust=0.5))
```


```{r}
grades|> drop_na(Exam)|>
  ggplot(aes(x = Group, y = Exam))+
  geom_violin()+
  ggtitle("Conditional grade distribution")+
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        plot.title = element_text(hjust=0.5))
```

## Question 8 

```{r}
grades|>
  group_by(Group)|>
  summarise("Missed Exam Count"=sum(is.na(Exam))) 

```

## Question 9

```{r}
grades|>
  group_by(Group)|>
  summarise("Missed Exam Count"=sum(is.na(Exam)))|>
  ggplot(aes(y = `Missed Exam Count`, x = Group))+
  geom_col()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

## Question 10

```{r}
long_grade <- grades|>
  pivot_longer(!c(Id,Group))
  
```

## Question 11

```{r}

missing_grades<-long_grade|> group_by(Id)|>
  summarise("Total number of missing grades" = sum(is.na(value)))

```

## Question 12 

```{r}
missing_grades|>
  ggplot(aes(x= `Total number of missing grades`))+
  geom_bar()+
  ggtitle("Distribution of missing grades per student")+
  theme(plot.title = element_text(hjust = 0.5))
  
```

## Question 13 

```{r}
long_grade|>
  filter(str_starts(name,"Exam"))|>
  group_by(Group)|>
  summarise("Missed Exam Count" = sum(is.na(value)))
```


## Question 14 

```{r}
MIA <- long_grade|>
  filter(str_starts(name,"Online"))|>
  group_by(Id)|>
  summarise("Missed online exam Count" = sum(is.na(value)))
```

## Question 15

```{r}


joined_table <- inner_join(grades,MIA,by = "Id")

joined_table|>
  mutate(`Missed online exam Count` = as.factor(`Missed online exam Count`))|>
  drop_na(Exam)|>
  ggplot(aes(x = `Missed online exam Count`, y = Exam))+
  geom_boxplot()+
  ylab("Final Exam score")+
  ggtitle("Final exam score", "Conditional on online exam attendance")+
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))


```
## Question 16 

```{r}
joined_table<- joined_table|>
  rowwise()|>
  mutate("Missing MCQ" = any(is.na(across(starts_with("MCQ")))))

MSQ_attendance<- joined_table|>
  select(Id,`Missing MCQ`)

```

## Question 17 

```{r}
p_missed_table <- joined_table|> 
  group_by(Group)|>
  summarise("P_missed" = sum(`Missing MCQ`==T)/n())
  
```


